config/routes.rb
Rails.application.routes.draw do
  
  root "books#index"

  resources :books do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence:true
  validates :body, presence: true, length: { minimum: 10 }
  validates :grade, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  
  belongs_to :book

  validates :body, presence: true, length: { minimum: 10 }

end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end 
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def book_params
    params.require(:book).permit(:title, :body, :grade, :status)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.create(comment_params)
    if @comment.save
      redirect_to book_path(@book), notice: 'Comentário adicionado com sucesso.'
    else
      redirect_to book_path(@book), alert: 'Erro ao adicionar comentário. Verifique os campos e tente novamente.'
    end
  end

  def update
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])
    if @comment.update(comment_params)
      redirect_to book_path(@book), notice: 'Comentário atualizado com sucesso.'
    else
      redirect_to book_path(@book), alert: 'Erro ao atualizar comentário. Verifique os campos e tente novamente.'
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])
    @comment.destroy
    redirect_to book_path(@book), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/_form.html.erb
<%= form_with model: book do |form| %>

<div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <%end%>
</div>

<div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% book.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <%end%>
</div>

<div>
    <%= form.label :grade %><br>
    <%= form.number_field :grade %>
    <% book.errors.full_messages_for(:grade).each do |message| %>
      <div><%= message %></div>
    <%end%>
</div>
 <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: book.status || 'public' %>
  </div>

<div>
    <%= form.submit "Enviar" %>     
</div>

<%end%>

app/views/books/edit.html.erb
<h2>Edite seu libro</h2>

<%= render "form", book: @book%>

app/views/books/index.html.erb
<h1>minha livraria</h1>

Our library has <%= Book.public_count %> Books and counting!

<ul>
    <% @book.each do |book|%>
     <% unless book.archived? %>
    <li>
      <%= link_to book.title, book%>
    </li>
    <%end%>
     <%end%>
</ul>

<%= link_to "Novo Livro", new_book_path%>

app/views/books/new.html.erb
<h2>REGISTRO DE LIVROS<h2>

<%= render "form", book: @book%>

app/views/books/show.html.erb
<h1><%=@book.title %></h1>

<p><%= @book.body %></p>

<p><%= @book.grade %></p>

<ul>
    <li><%= link_to "Editar conteúdo", edit_book_path(@book) %></li>
    <li><%= link_to "Apagar livro", book_path(@book), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
</ul>

<h2>Comments</h2>

<%= render @book.comments %>

<h2>Adicione um comentário:</h2>

<%= render 'comments/form', book: @book, comment: @book.comments.build %>

app/views/comments/_comment.html.erb
<% book = comment.book %>

<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <%= form_with model: [comment.book, comment], local: true do |form| %>
    <p>
      <%= form.label :status %><br>
      <%= form.select :status, Visible::VALID_STATUSES, selected: comment.status %>
    </p>

    <%= form.submit "Update Status" %>
  <% end %>

  <%= link_to "Deletar comentário", [comment.book, comment],
  data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
  }%>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [comment.book, comment], local: true do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: comment.status %>
  </p>
  <p>
    <%= form.submit "Save" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>